### ISSUE TITLE
Infinite Stamina config does not work

### ISSUE THREAD

**Issue by aaronhowser1** [alRex-U/ParCool#159]
**Summary**
```toml
[Stamina]
	#Limitation of max stamina
	#Range: 300 ~ 100000
	max_value_of_stamina = 10000
	#Limitation of max stamina recovery
	#Range: 1 ~ 10000
	max_value_of_stamina_recovery = 1000
	#Allow Infinite Stamina
	infinite_stamina = true
```
and yet I use up stamina when doing parkour

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ParCool-1.19.2-3.0.0.3-B
+ Forge Version (optional):
